language: node_js
cache:
    npm: false
node_js:
- 8
sudo: required
services:
- docker
before_install:
- docker pull selenium/standalone-chrome:latest
before_script:
- docker run -d --net=host --shm-size=2g selenium/standalone-chrome:latest
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
script:
- npm install
- npm install selenium-server
- ./node_modules/.bin/selenium-standalone install
- npx codeceptjs run --grep displayed
